server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/gdsc_devlog?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nathan
    password: seoulman2000!
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update # drop exist table and create new table
    properties:
      hibernate:
        format-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
